name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 9.x
  pull_request:
    branches:
      - 9.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create SSH key
        shell: bash
        env:
          SSH_KEY: ${{ secrets.ci_deploy_key }}
          SSH_USER: ${{ secrets.ci_production_username }}
          SSH_HOST: ${{ secrets.ci_production_host }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      - name: Deploy
        shell: bash
        env:
          DEPLOY_PATH: ${{ secrets.ci_deploy_path }}
        run: |
          ssh production "cd $DEPLOY_PATH/scripts && dep deploy"
